apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gangadhar0416/backend:latest
          env:
          - name: SQL_PASSWORD
            value: admin123
          - name: SQL_USERNAME
            value: admin
          - name : SQL_HOST
            value: database-1.c7vq7maqswxz.us-east-1.rds.amazonaws.com
          ports:
            - containerPort: 5000
          imagePullPolicy: Always